version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DEFAULT_WORKSPACE=/personal-blog
    volumes:
      - ./config:/config
      - ../personal-blog:/personal-blog
    ports:
      - 8443:8443
    restart: unless-stopped
