version: '3'

services:
  database:
    image: postgres:alpine3.18
    container_name: nc-postgres
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - nc-db-postgres:/var/lib/postgresql/data:z
    restart: unless-stopped

  cache:
    image: redis:alpine3.18
    container_name: nc-redis
    network_mode: bridge
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - nc-cache-redis:/data
    depends_on:
      - database
    restart: unless-stopped

  app:
    image: lscr.io/linuxserver/nextcloud:26.0.2
    container_name: nc-nextcloud
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - REDIS_HOST=cache
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./config:/config
      - ./data:/data
      - nc-app-nextcloud:/var/www/html
    ports:
      - 443:443
    depends_on:
      - database
      - cache
    restart: unless-stopped

  web:
    image: lscr.io/linuxserver/nginx:1.24.0
    container_name: nc-nginx
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - nc-web-nginx:/config
    volumes_from:
      - app
    depends_on:
      - app
    restart: unless-stopped

volumes:
  nc-db-postgres:
  nc-cache-redis:
  nc-app-nextcloud:
  nc-web-nginx:
