# Following exactly this before deleting above

version: '3'

services:
  database:
    image: postgres:alpine
    container_name: postgres
    network_mode: bridge
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - db-postgres:/var/lib/postgresql/data:z
    restart: unless-stopped

  cache:
    image: redis:alpine
    container_name: redis
    network_mode: bridge
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - cache-redis:/data
    depends_on:
      - database
    restart: unless-stopped

  app:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - REDIS_HOST=cache
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./nextcloud-config:/config
      - app-data:/data
      - app-nextcloud:/var/www/html
    ports:
      - 443:443
    depends_on:
      - database
      - cache
    restart: unless-stopped

  web:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - web-nginx:/config
    volumes_from:
      - app
    depends_on:
      - app
    restart: unless-stopped

volumes:
  db-postgres:
  cache-redis:
  app-data:
  app-nextcloud:
  web-nginx:


# container names need prefix